### ISSUE TITLE
Requirement to run from within flutter-desktop-embedding is obsolete

### ISSUE THREAD

**Issue by stuartmorgan** [tomaszpolanski/flutter-presentations#3]
FYI, this step of your README:

> Copy flutter-presentations into flutter-desktop-embedding folder

isn't necessary; the desktop platform folders in flutter-desktop are fully relocatable. All the dependencies on the rest of the flutter-desktop-embedding repository that they used to contain are gone.

**Comment by tomaszpolanski** [comment]
Thanks, @stuartmorgan for the heads up, will update readme. 
Thank you also for all the amazing work for desktop!
